name: xizmatbor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.2.1
  get_it: ^9.0.5
  http: ^1.5.0
  modal_bottom_sheet: ^3.0.0
  permission_handler: ^12.0.1
  yandex_mapkit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
   - family: Unbounded
     fonts:
       - asset: assets/fonts/Unbounded/static/Unbounded-Regular.ttf
       - asset: assets/fonts/Unbounded/static/Unbounded-ExtraBold.ttf
         weight: 800
       - asset: assets/fonts/Unbounded/static/Unbounded-Bold.ttf
         weight: 700
       - asset: assets/fonts/Unbounded/static/Unbounded-Medium.ttf
         weight: 500
       - asset: assets/fonts/Unbounded/static/Unbounded-Light.ttf
         weight: 400
   - family: VelaSans
     fonts:
     - asset: assets/fonts/VelaSans/VelaSans-Regular.ttf
     - asset: assets/fonts/VelaSans/VelaSans-ExtraBold.ttf
       weight: 800
     - asset: assets/fonts/VelaSans/VelaSans-Bold.ttf
       weight: 700
     - asset: assets/fonts/VelaSans/VelaSans-SemiBold.ttf
       weight: 600
     - asset: assets/fonts/VelaSans/VelaSans-Medium.ttf
       weight: 500
     - asset: assets/fonts/VelaSans/VelaSans-Light.ttf
       weight: 400
  uses-material-design: true
  assets:
    - assets/icons/services/
    - assets/images/
    - assets/icons/
    - assets/